"""Script for rendering EDA reports from report.json with Jinja2 template."""

from jinja2 import Template
import os
import json
import base64

def image_to_base64(image_path):
    """
    Convert an image file to base64 data URI.

    Args:
        image_path (str): Path to the image file

    Returns:
        str: Base64 data URI string
    """
    if not os.path.exists(image_path):
        return ""

    with open(image_path, 'rb') as image_file:
        encoded_string = base64.b64encode(image_file.read()).decode('utf-8')

        # Get file extension to determine MIME type
        ext = os.path.splitext(image_path)[1].lower()
        if ext == '.png':
            mime_type = 'image/png'
        elif ext == '.jpg' or ext == '.jpeg':
            mime_type = 'image/jpeg'
        elif ext == '.gif':
            mime_type = 'image/gif'
        elif ext == '.webp':
            mime_type = 'image/webp'
        else:
            mime_type = 'image/png'  # default

        return f'data:{mime_type};base64,{encoded_string}'


def generate_eda_report(template_path, output_path, data, images_base_path="outputs/"):
    """
    Generate an EDA report using the Jinja2 template.

    Args:
        template_path (str): Path to the HTML template file
        output_path (str): Path where the rendered HTML will be saved
        data (dict): Dictionary containing all the data to inject into the template
        images_base_path (str): Base path where images are located (default: "outputs/")
    """

    # Read the template
    with open(template_path, 'r', encoding='utf-8') as f:
        template_content = f.read()

    # Create Jinja2 template
    template = Template(template_content)

    # Render the template with data
    rendered_html = template.render(**data)

    # Write the rendered HTML to output file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(rendered_html)

    print(f"✅ EDA report generated successfully: {output_path}")


def load_report_json(report_json_path):
    """
    Load and parse report.json file.

    Args:
        report_json_path (str): Path to report.json file

    Returns:
        dict: Parsed JSON data
    """
    if not os.path.exists(report_json_path):
        raise FileNotFoundError(f"Report JSON file not found: {report_json_path}")
    
    with open(report_json_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def prepare_data_from_report(report_data, images_base_path="outputs/"):
    """
    Transform report.json data into template-ready format.

    Args:
        report_data (dict): The loaded report.json data
        images_base_path (str): Base path for images

    Returns:
        dict: Data formatted for Jinja2 template rendering
    """
    # Extract header info from sections
    header_title = "🦉 OwlMix EDA Report"
    header_subtitle = "Exploratory Data Analysis for Marketing Mix Modeling"
    title = "OwlMix EDA Report"
    generator = "Generated by OwlMix EDA"
    report_date = None
    
    # Extract basic_info, correlation_matrix, lag_correlation from sections
    basic_info = None
    correlation_matrix = None
    lag_correlation = None
    
    if "sections" in report_data:
        for section in report_data["sections"]:
            if "header_title" in section:
                header_title = section["header_title"]
            if "header_subtitle" in section:
                header_subtitle = section["header_subtitle"]
            if "title" in section:
                title = section["title"]
            if "generator" in section:
                generator = section["generator"]
            if "report_date" in section:
                report_date = section["report_date"]
            if "basic_info" in section:
                basic_info = section["basic_info"]
            if "correlation_matrix" in section:
                correlation_matrix = section["correlation_matrix"]
            if "lag_correlation" in section:
                lag_correlation = section["lag_correlation"]
    
    # Process charts and convert image paths to base64
    charts = []
    if "charts" in report_data:
        for chart in report_data["charts"]:
            chart_item = {
                "title": chart.get("title", "Chart"),
                "description": chart.get("description", ""),
                "alt_text": chart.get("alt_text", chart.get("title", "Chart"))
            }
            
            # Check for existing image_data (already base64)
            if "image_data" in chart and chart["image_data"]:
                chart_item["image_data"] = chart["image_data"]
            # Otherwise try to load from file paths
            else:
                for key in ["correlation_chart", "time_series_chart", 
                           "outliers_chart", "lag_correlation_chart"]:
                    if key in chart and chart[key]:
                        image_path = chart[key]
                        base64_data = image_to_base64(image_path)
                        if base64_data:
                            chart_item["image_data"] = base64_data
                            break
            
            charts.append(chart_item)
    
    # Prepare template data
    template_data = {
        "title": title,
        "header_title": header_title,
        "header_subtitle": header_subtitle,
        "generator": generator,
        "report_date": report_date,
        # "sections": report_data.get("sections", []),
        "basic_info": basic_info,
        "corr_matrix": correlation_matrix,
        "lag_corr": lag_correlation,
        "charts": charts
    }
    
    return template_data


if __name__ == "__main__":
    # File paths
    template_path = "outputs/eda_report_template.html"
    output_path = "outputs/rendered_eda_report.html"
    report_json_path = "outputs/report.json"
    images_base_path = "outputs"

    try:
        # Load report.json
        print(f"📖 Loading report from: {report_json_path}")
        report_data = load_report_json(report_json_path)
        
        # Prepare data for template
        print("🔄 Processing report data...")
        data = prepare_data_from_report(report_data, images_base_path)
        # print(data)
        
        # Generate the report
        print(f"🎨 Rendering template: {template_path}")
        generate_eda_report(template_path, output_path, data, images_base_path)
        print(f"✨ Report complete: {output_path}")
        
    except FileNotFoundError as e:
        print(f"❌ Error: {e}")
        print(f"   Ensure report.json exists at: {report_json_path}")
    except Exception as e:
        print(f"❌ Error generating report: {e}")
        raise
