acf_pacf:
  columns:
    - digital_imp
    - radio_spend
  n_lags: 10
  precision: 2

vif:
  precision: 2

correlation:
  n_lags: 8
  precision: 5

box_plot:
  columns:
    - tv_spend
    - digital_spend
    - radio_spend
    - tv_grp
    - digital_imp
  n_plot_per_row: 5
  method: zscore
  threshold: 1.7

ccf:
  feature_columns:
    - tv_spend
    - digital_spend
  max_lag: 3

response_summary:
  feature_columns:
    - tv_spend
    - digital_spend
    - radio_spend
    - tv_grp
    - digital_imp
  target_column: sales
