# src/owlmix/report/renderer.py
import os
from jinja2 import Template


class HTMLRenderer:

    def __init__(self, template_name: str = "report.html", template_path: str = None):
        """
        template_name: file name (e.g., report.html)
        template_path: full custom path (highest priority)
        """

        self.template_name = template_name

        # Step 1: If full path is explicitly provided
        if template_path:
            template_dir = os.path.dirname(template_path)
            template_file = os.path.basename(template_path)

        else:
            # Step 2: Look for user-level templates folder
            user_templates_dir = os.path.join(os.getcwd(), "templates")

            if os.path.exists(user_templates_dir):
                candidate = os.path.join(user_templates_dir, template_name)

                if os.path.exists(candidate):
                    template_dir = user_templates_dir
                    template_file = template_name
                else:
                    # templates folder exists but file missing → fallback
                    template_dir, template_file = self._get_default_template()

            else:
                # Step 3: fallback to package default
                template_dir, template_file = self._get_default_template()

        with open(os.path.join(template_dir, template_name), "r", encoding="utf-8") as f:
            template_content = f.read()

        self.template = Template(template_content)

    def _get_default_template(self):
        default_dir = os.path.join(
            os.path.dirname(__file__), "default_template"
        )
        return default_dir, "report.html"

    def render(self, data: dict, output_path: str) -> str:
        # Render the template with data
        template_data = self._prepare_data_from_report(data)
        rendered_html = self.template.render(**template_data)

        with open(output_path, "w") as f:
            f.write(rendered_html)

        return output_path

    def _prepare_data_from_report(self, report_data):
        # Extract header info from sections
        header_title = "🦉 OwlMix EDA Report"
        header_subtitle = "Exploratory Data Analysis for Marketing Mix Modeling"
        title = "OwlMix EDA Report"
        generator = "Generated by OwlMix EDA"
        report_date = None

        # Extract basic_info, correlation_matrix, lag_correlation from sections
        basic_info = None
        correlation_matrix = None
        lag_correlation = None

        if "sections" in report_data:
            for section in report_data["sections"]:
                if "header_title" in section:
                    header_title = section["header_title"]

                if "header_subtitle" in section:
                    header_subtitle = section["header_subtitle"]

                if "title" in section:
                    title = section["title"]

                if "generator" in section:
                    generator = section["generator"]

                if "report_date" in section:
                    report_date = section["report_date"]

                if "basic_info" in section:
                    basic_info = section["basic_info"]

                if "time_comparison" in section:
                    time_comparison = section["time_comparison"]

                if "vif" in section:
                    vif = section["vif"]

                if "time_aggregator" in section:
                    time_aggregator = section["time_aggregator"]

                if "correlation_matrix" in section:
                    correlation_matrix = section["correlation_matrix"]

                if "lag_correlation" in section:
                    lag_correlation = section["lag_correlation"]

        # Process charts and convert image paths to base64
        charts = []
        if "charts" in report_data:
            for chart in report_data["charts"]:
                chart_item = {
                    "title": chart.get("title", "Chart"),
                    "description": chart.get("description", ""),
                    "alt_text": chart.get("alt_text", chart.get("title", "Chart"))
                }

                # Check for existing image_data (already base64)
                if "image_data" in chart and chart["image_data"]:
                    chart_item["image_data"] = chart["image_data"]
                # Otherwise try to load from file paths
                else:
                    for key in ["correlation_chart", "time_series_chart",
                                "outliers_chart", "lag_correlation_chart"]:
                        if key in chart and chart[key]:
                            image_path = chart[key]
                            base64_data = self.image_to_base64(image_path)
                            if base64_data:
                                chart_item["image_data"] = base64_data
                                break

                charts.append(chart_item)

        # Prepare template data
        template_data = {
            "title": title,
            "header_title": header_title,
            "header_subtitle": header_subtitle,
            "generator": generator,
            "report_date": report_date,
            "basic_info": basic_info,
            "corr_matrix": correlation_matrix,
            "lag_corr": lag_correlation,
            "time_comparison": time_comparison,
            "vif": vif,
            # "time_aggregator": time_aggregator,
            "charts": charts
        }

        return template_data

    def image_to_base64(image_path: str):
        """Convert an image file to base64 data URI."""

        if not os.path.exists(image_path):
            return ""

        with open(image_path, 'rb') as image_file:
            encoded_string = base64.b64encode(image_file.read()).decode('utf-8')

            # Get file extension to determine MIME type
            ext = os.path.splitext(image_path)[1].lower()
            if ext == '.png':
                mime_type = 'image/png'
            elif ext == '.jpg' or ext == '.jpeg':
                mime_type = 'image/jpeg'
            elif ext == '.gif':
                mime_type = 'image/gif'
            elif ext == '.webp':
                mime_type = 'image/webp'
            else:
                mime_type = 'image/png'  # default

            return f'data:{mime_type};base64,{encoded_string}'
