# src/owlmix/report/renderer.py
import os
import base64
from jinja2 import Template


class HTMLRenderer:

    DEFAULT_HEADERS = {
        "header_title": "🦉 OwlMix EDA Report",
        "header_subtitle": "Exploratory Data Analysis for Marketing Mix Modeling",
        "title": "OwlMix EDA Report",
        "generator": "Generated by OwlMix EDA",
    }

    MIME_TYPES = {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".gif": "image/gif",
        ".webp": "image/webp"
    }

    def __init__(self, template_name: str = "report.html", template_path: str = None):
        """Initialize renderer with template."""
        self.template_name = template_name
        template_dir, template_file = self._resolve_template_path(template_path, template_name)

        with open(os.path.join(template_dir, template_file), mode="r", encoding="utf-8") as f:
            self.template = Template(f.read())

    def _resolve_template_path(self, template_path: str, template_name: str) -> tuple:
        """Resolve template directory and filename with priority order."""
        # Priority 1: Explicit full path
        if template_path:
            return os.path.dirname(template_path), os.path.basename(template_path)

        # Priority 2: User templates folder
        user_templates_dir = os.path.join(os.getcwd(), "templates")
        candidate = os.path.join(user_templates_dir, template_name)
        if os.path.exists(candidate):
            return user_templates_dir, template_name

        # Priority 3: Package default
        return self._get_default_template()

    def _get_default_template(self) -> tuple:
        """Get default template location."""
        default_dir = os.path.join(os.path.dirname(__file__), "default_template")
        return default_dir, "report.html"

    def render(self, data: dict, output_path: str) -> str:
        """Render template with data and write to file."""
        template_data = self._prepare_data_from_report(data)
        rendered_html = self.template.render(**template_data)

        with open(output_path, mode="w") as f:
            f.write(rendered_html)

        return output_path

    def _prepare_data_from_report(self, report_data: dict) -> dict:
        """Extract and prepare all data from report."""
        # Initialize defaults
        section_data = self._extract_sections(report_data)
        charts = self._process_charts(report_data)

        return {
            "title": section_data["title"],
            "header_title": section_data["header_title"],
            "header_subtitle": section_data["header_subtitle"],
            "generator": section_data["generator"],
            "report_date": section_data["report_date"],
            "basic_info": section_data["basic_info"],
            "corr_matrix": section_data["correlation_matrix"],
            "lag_corr": section_data["lag_correlation"],
            "time_comparison": section_data["time_comparison"],
            "causality_test": section_data["causality_test"],
            "vif": section_data["vif"],
            "acf_pacf": section_data["acf_pacf"],
            "charts": charts,
        }

    def _extract_sections(self, report_data: dict) -> dict:
        """Extract and merge all section data from report."""
        # Define all expected keys with defaults
        keys = {
            "header_title": self.DEFAULT_HEADERS["header_title"],
            "header_subtitle": self.DEFAULT_HEADERS["header_subtitle"],
            "title": self.DEFAULT_HEADERS["title"],
            "generator": self.DEFAULT_HEADERS["generator"],
            "report_date": None,
            "basic_info": None,
            "time_comparison": None,
            "causality_test": None,
            "vif": None,
            "acf_pacf": None,
            "time_aggregator": None,
            "correlation_matrix": None,
            "lag_correlation": None,
        }

        # Merge all sections (later sections override earlier ones)
        if "sections" in report_data:
            for section in report_data["sections"]:
                for key in keys:
                    if key in section:
                        keys[key] = section[key]

        return keys

    def _process_charts(self, report_data: dict) -> list:
        """Process and convert charts to base64."""
        charts = []

        if "charts" not in report_data:
            return charts

        for chart in report_data["charts"]:
            chart_item = {
                "title": chart.get("title", "Chart"),
                "description": chart.get("description", ""),
                "alt_text": chart.get("alt_text", chart.get("title", "Chart")),
            }

            # Try to get image data (priority: existing base64, then file paths)
            if "image_data" in chart and chart["image_data"]:
                chart_item["image_data"] = chart["image_data"]
            else:
                for key in ["correlation_chart", "time_series_chart", "outliers_chart", "lag_correlation_chart"]:
                    if key in chart and chart[key]:
                        base64_data = self.image_to_base64(chart[key])
                        if base64_data:
                            chart_item["image_data"] = base64_data
                            break

            charts.append(chart_item)

        return charts

    def image_to_base64(self, image_path: str) -> str:
        """Convert image file to base64 data URI."""
        if not os.path.exists(image_path):
            return ""

        with open(image_path, mode="rb") as image_file:
            encoded = base64.b64encode(image_file.read()).decode("utf-8")

        ext = os.path.splitext(image_path)[1].lower()
        mime_type = self.MIME_TYPES.get(ext, "image/png")

        return f"data:{mime_type};base64,{encoded}"
