import pandas as pd
from typing import Dict, Protocol, Any, Self
from pathlib import Path
from ...config.config_builder import ConfigBuilder

class ReportBuilderProtocol(Protocol):
    df: pd.DataFrame
    target_col: str
    date_col: str
    config: ConfigBuilder
    def add_all_sections(self) -> None: ...
    def include_sections(self, sections: list[str]) -> None: ...
    def exclude_sections(self, sections: list[str]) -> None: ...
    def add_section(self, name: str, data: Dict[str, Any], chart: Dict[str, Any]) -> Self: ...
    def add_section_by_name(self, name: str) -> Self: ...
    def build(self, output_path: str | Path) -> Dict[str, Any]: ...
    def image_to_base64(self, path: str | Path) -> str: ...
    def save(self, path: str | Path) -> None: ...